version: "3.9"
services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-bot
    env_file:
      - .env
# Ha a botod folyamatosan fut, nincs szükség extra restart policy-re, de hozzáadhatod:
    restart: unless-stopped
