// <auto-generated />
using System;
using DC_bot.Persistence.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DC_bot.Persistence.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20260425193122_AddPlaybackStateQueueItemId")]
    partial class AddPlaybackStateQueueItemId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DC_bot.Persistence.Entities.GuildDataEntity", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<bool>("IsPremium")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_premium");

                    b.Property<DateTimeOffset?>("PremiumUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("premium_until_utc");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("now()");

                    b.HasKey("GuildId");

                    b.ToTable("guild_data", (string)null);
                });

            modelBuilder.Entity("DC_bot.Persistence.Entities.GuildPlaybackStateEntity", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<string>("CurrentTrackIdentifier")
                        .HasColumnType("text")
                        .HasColumnName("current_track_identifier");

                    b.Property<bool>("IsRepeating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_repeating");

                    b.Property<bool>("IsRepeatingList")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_repeating_list");

                    b.Property<long?>("QueueItemId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("now()");

                    b.HasKey("GuildId");

                    b.ToTable("guild_playback_state", (string)null);
                });

            modelBuilder.Entity("DC_bot.Persistence.Entities.GuildPremiumAuditEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("ChangedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("changed_by_user_id");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<bool>("NewIsPremium")
                        .HasColumnType("boolean")
                        .HasColumnName("new_is_premium");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<bool>("OldIsPremium")
                        .HasColumnType("boolean")
                        .HasColumnName("old_is_premium");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "ChangedAtUtc");

                    b.ToTable("guild_premium_audit", (string)null);
                });

            modelBuilder.Entity("DC_bot.Persistence.Entities.GuildQueueItemEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AddedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<DateTimeOffset?>("PlayedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("played_at_utc");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<DateTimeOffset?>("SkippedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("skipped_at_utc");

                    b.Property<short>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("state");

                    b.Property<string>("TrackIdentifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("track_identifier");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "Position")
                        .IsUnique();

                    b.HasIndex("GuildId", "State", "Position");

                    b.ToTable("guild_queue_item", (string)null);
                });

            modelBuilder.Entity("DC_bot.Persistence.Entities.GuildRepeatListItemEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AddedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("TrackIdentifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("track_identifier");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "Position")
                        .IsUnique();

                    b.ToTable("guild_repeat_list_item", (string)null);
                });

            modelBuilder.Entity("DC_bot.Persistence.Entities.GuildPlaybackStateEntity", b =>
                {
                    b.HasOne("DC_bot.Persistence.Entities.GuildDataEntity", "Guild")
                        .WithOne("PlaybackState")
                        .HasForeignKey("DC_bot.Persistence.Entities.GuildPlaybackStateEntity", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("DC_bot.Persistence.Entities.GuildPremiumAuditEntity", b =>
                {
                    b.HasOne("DC_bot.Persistence.Entities.GuildDataEntity", "Guild")
                        .WithMany("PremiumAuditEntries")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("DC_bot.Persistence.Entities.GuildQueueItemEntity", b =>
                {
                    b.HasOne("DC_bot.Persistence.Entities.GuildDataEntity", "Guild")
                        .WithMany("QueueItems")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("DC_bot.Persistence.Entities.GuildRepeatListItemEntity", b =>
                {
                    b.HasOne("DC_bot.Persistence.Entities.GuildDataEntity", "Guild")
                        .WithMany("RepeatListItems")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("DC_bot.Persistence.Entities.GuildDataEntity", b =>
                {
                    b.Navigation("PlaybackState");

                    b.Navigation("PremiumAuditEntries");

                    b.Navigation("QueueItems");

                    b.Navigation("RepeatListItems");
                });
#pragma warning restore 612, 618
        }
    }
}
