name: .NET Core DC Bot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Clean
      run: |
        Remove-Item -Recurse -Force bin,obj -ErrorAction SilentlyContinue

    - name: Restore
      run: dotnet restore ".\DC bot.sln"

    - name: Build ${{ matrix.configuration }}
      run: dotnet build --configuration ${{ matrix.configuration }} --no-restore

    - name: Test (Debug only)
      if: matrix.configuration == 'Debug'
      env:
        BOT_PREFIX: ${{ secrets.BOT_PREFIX }}
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        LAVALINK_HOSTNAME: ${{ secrets.LAVALINK_HOSTNAME }}
        LAVALINK_PASSWORD: ${{ secrets.LAVALINK_PASSWORD }}
        LAVALINK_PORT: ${{ secrets.LAVALINK_PORT }}
        LAVALINK_SECURED: ${{ secrets.LAVALINK_SECURED }}
      run: dotnet test ".\DC bot tests\DC bot tests.csproj" --logger trx --results-directory TestResults

    - name: Upload tests
      if: matrix.configuration == 'Debug'
      uses: actions/upload-artifact@v4
      with:
        name: Test-Results-${{ matrix.configuration }}
        path: TestResults
