name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-debug:
    runs-on: windows-latest
    env:
      Solution_Name: '.\DC bot.sln'
      Test_Project_Path: '.\DC bot tests\DC bot tests.csproj'
      BOT_PREFIX: ${{ secrets.BOT_PREFIX }}
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      LAVALINK_HOSTNAME: ${{ secrets.LAVALINK_HOSTNAME }}
      LAVALINK_PASSWORD: ${{ secrets.LAVALINK_PASSWORD }}
      LAVALINK_PORT: ${{ secrets.LAVALINK_PORT }}
      LAVALINK_SECURED: ${{ secrets.LAVALINK_SECURED }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Clean project
      run: |
        Remove-Item -Recurse -Force bin, obj -ErrorAction SilentlyContinue

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Debug
      run: dotnet build --configuration Debug --no-restore

    - name: Run tests
      run: dotnet test --logger trx --results-directory TestResults

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: Test-Results-Debug
        path: TestResults

  build-release:
    runs-on: windows-latest
    needs: build-debug  # Csak akkor fut le, ha a build-debug sikeres
    env:
      Solution_Name: '.\DC bot.sln'
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Clean project
      run: |
        Remove-Item -Recurse -Force bin, obj -ErrorAction SilentlyContinue

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Release
      run: dotnet build --configuration Release --no-restore
