name: Enforce Branch Naming

on:
  create:
    branches:
      - '**'

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          if [[ ! "$BRANCH_NAME" =~ ^(feature|bugfix)/.+$ ]]; then
            echo "❌ ERROR: Invalid branch name '$BRANCH_NAME'. Use 'feature/{name}' or 'bugfix/{name}'"
            exit 1
          fi
